#!/usr/bash

for i in {1..3}
do
	echo "Running Iteration: $i"
	top -b -n1 | grep "Cpu(s)"
	top -b -n1 | grep "Cpu(s)"  >> consumptions.txt
	if [ $i != 3 ]; then
		echo "-----------------------------------------------------"
	fi
sleep 5
done
